export const STATIC_PRODUCTS = [
  {
    id: 'static-1',
    slug: 'mika-8kg-front-load-inverter-washing-machine-static-1',
    name: 'MIKA 8kg Front Load Inverter Washing Machine',
    brand: 'Mika',
    category: 'KITCHEN',
    subcategory: 'washing-machines',
    price: 48999,
    comparePrice: 59999,
    images: ['https://picsum.photos/id/1015/800/800'],
    description: 'Inverter technology, 8kg capacity, perfect for Kenyan homes',
    stock: 10,
    isActive: true,
    isFeatured: true,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-2',
    slug: 'samsung-galaxy-a35-5g-smartphone-static-2',
    name: 'Samsung Galaxy A35 5G Smartphone',
    brand: 'Samsung',
    category: 'SMARTPHONES',
    subcategory: 'android-phones',
    price: 44999,
    comparePrice: 52999,
    images: ['https://picsum.photos/id/201/800/800'],
    description: '128GB storage, 50MP camera, long battery life',
    stock: 15,
    isActive: true,
    isFeatured: true,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-3',
    slug: 'hisense-43-smart-uhd-tv-static-3',
    name: 'Hisense 43" Smart UHD TV',
    brand: 'Hisense',
    category: 'AUDIO_TV',
    subcategory: 'televisions',
    price: 32999,
    comparePrice: 39999,
    images: ['https://picsum.photos/id/301/800/800'],
    description: '4K UHD, Android TV, Dolby Vision',
    stock: 8,
    isActive: true,
    isFeatured: true,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-4',
    slug: 'hp-15s-intel-core-i5-laptop-static-4',
    name: 'HP 15s Intel Core i5 Laptop',
    brand: 'HP',
    category: 'LAPTOPS',
    subcategory: 'laptops',
    price: 68999,
    comparePrice: 79999,
    images: ['https://picsum.photos/id/401/800/800'],
    description: '16GB RAM, 512GB SSD, Windows 11',
    stock: 6,
    isActive: true,
    isFeatured: true,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-5',
    slug: 'ramtons-50l-chest-freezer-static-5',
    name: 'Ramtons 50L Chest Freezer',
    brand: 'Ramtons',
    category: 'KITCHEN',
    subcategory: 'freezers',
    price: 18999,
    comparePrice: 22999,
    images: ['https://picsum.photos/id/501/800/800'],
    description: 'Energy efficient, ideal for Kenyan households',
    stock: 12,
    isActive: true,
    isFeatured: false,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-6',
    slug: 'tecno-spark-20-pro-static-6',
    name: 'Tecno Spark 20 Pro',
    brand: 'Tecno',
    category: 'SMARTPHONES',
    subcategory: 'android-phones',
    price: 22999,
    comparePrice: 27999,
    images: ['https://picsum.photos/id/601/800/800'],
    description: '108MP camera, 256GB storage',
    stock: 20,
    isActive: true,
    isFeatured: false,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-7',
    slug: 'lg-1-5hp-inverter-air-conditioner-static-7',
    name: 'LG 1.5HP Inverter Air Conditioner',
    brand: 'LG',
    category: 'SMART_HOME',
    subcategory: 'air-conditioners',
    price: 89999,
    comparePrice: 109999,
    images: ['https://picsum.photos/id/701/800/800'],
    description: 'Fast cooling, energy saving',
    stock: 5,
    isActive: true,
    isFeatured: false,
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 'static-8',
    slug: 'sony-55-bravia-oled-tv-static-8',
    name: 'Sony 55" Bravia OLED TV',
    brand: 'Sony',
    category: 'AUDIO_TV',
    subcategory: 'televisions',
    price: 129999,
    comparePrice: 149999,
    images: ['https://picsum.photos/id/801/800/800'],
    description: 'Premium picture quality',
    stock: 4,
    isActive: true,
    isFeatured: false,
    avgRating: 0,
    reviewCount: 0,
  },
];
