// Static product catalogue — shown when DB is unavailable
export type StaticProduct = {
  id: string; name: string; slug: string; brand: string;
  category: string; subcategory: string;
  price: number; comparePrice: number;
  isFeatured: boolean; images: string[];
  avgRating: number; reviewCount: number;
  description?: string;
};

export const STATIC_PRODUCTS: StaticProduct[] = [
  {
    id:           "mika-side-by-side-fridge-442l-inverter",
    name:         "MIKA Side-by-Side No Frost Fridge 442L Inverter",
    slug:         "mika-side-by-side-fridge-442l-inverter",
    brand:        "Mika",
    category:     "KITCHEN",
    subcategory:  "fridges",
    price:        89999,
    comparePrice: 99999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.8, reviewCount: 0,
    description: "MIKA Side-by-Side No Frost Fridge with Inverter technology. 442L capacity, energy-efficient, with digital display and multiple cooling zones.",
  },
  {
    id:           "mika-water-dispenser-hot-electric-mwd2304wb",
    name:         "MIKA Water Dispenser Hot & Electric Cooling Cabinet White/Black",
    slug:         "mika-water-dispenser-hot-electric-mwd2304wb",
    brand:        "Mika",
    category:     "KITCHEN",
    subcategory:  "water-dispensers",
    price:        15999,
    comparePrice: 18999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.6, reviewCount: 0,
    description: "MIKA Hot & Electric Cooling Water Dispenser with cabinet storage. White/Black finish. Delivers hot and cold water instantly.",
  },
  {
    id:           "mika-water-dispenser-3tap-mwd2307bg",
    name:         "MIKA Water Dispenser 3-Tap Hot Normal & Electric Cooling Black/Grey",
    slug:         "mika-water-dispenser-3tap-mwd2307bg",
    brand:        "Mika",
    category:     "KITCHEN",
    subcategory:  "water-dispensers",
    price:        18999,
    comparePrice: 22999,
    isFeatured:   false,
    images:       ["https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.7, reviewCount: 0,
    description: "MIKA 3-tap water dispenser — hot, normal, and cold. Electric cooling system for crisp cold water. Sleek Black/Grey design.",
  },
  {
    id:           "mika-bottom-load-dispenser-mwdb2804bs",
    name:         "MIKA Bottom Load Water Dispenser Compressor Cooling 3-Tap Black/Silver",
    slug:         "mika-bottom-load-dispenser-mwdb2804bs",
    brand:        "Mika",
    category:     "KITCHEN",
    subcategory:  "water-dispensers",
    price:        22999,
    comparePrice: 27999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.9, reviewCount: 0,
    description: "Bottom-load design — no heavy lifting. Compressor cooling for faster, colder water. 3-tap system. Black/Silver premium finish.",
  },
  {
    id:           "mika-8kg-front-load-inverter-washer",
    name:         "MIKA 8kg Front Load Inverter Washing Machine Dark Silver",
    slug:         "mika-8kg-front-load-inverter-washer",
    brand:        "Mika",
    category:     "KITCHEN",
    subcategory:  "washing-machines",
    price:        62999,
    comparePrice: 74999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.8, reviewCount: 0,
    description: "MIKA 8kg front-load inverter washing machine. Energy-efficient inverter motor, multiple wash programs, steam wash option. Dark Silver.",
  },
  {
    id:           "ramtons-twin-tub-semi-auto-rw215",
    name:         "Ramtons Twin Tub Semi-Automatic 10kg Washer 6kg Spin",
    slug:         "ramtons-twin-tub-semi-auto-rw215",
    brand:        "Ramtons",
    category:     "KITCHEN",
    subcategory:  "washing-machines",
    price:        18500,
    comparePrice: 21000,
    isFeatured:   false,
    images:       ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.5, reviewCount: 0,
    description: "Ramtons twin-tub semi-automatic washer. 10kg wash capacity, 6kg spin capacity. Manual controls, durable design for everyday use.",
  },
  {
    id:           "hisense-5-burner-90cm-gas-hob",
    name:         "Hisense 5-Burner 90cm Built-In Gas Hob Black Stainless Steel",
    slug:         "hisense-5-burner-90cm-gas-hob",
    brand:        "Hisense",
    category:     "KITCHEN",
    subcategory:  "built-in",
    price:        34999,
    comparePrice: 40999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.7, reviewCount: 0,
    description: "Hisense 5-burner 90cm built-in gas hob. Cast iron pan supports, auto-ignition, FFD safety valves. Black tempered glass surface.",
  },
  {
    id:           "hisense-4-burner-60cm-gas-hob",
    name:         "Hisense 4-Burner 60cm Built-In Gas Hob Black Glass",
    slug:         "hisense-4-burner-60cm-gas-hob",
    brand:        "Hisense",
    category:     "KITCHEN",
    subcategory:  "built-in",
    price:        24999,
    comparePrice: 29999,
    isFeatured:   false,
    images:       ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.6, reviewCount: 0,
    description: "Hisense 4-burner 60cm built-in gas hob with black glass surface. Auto ignition, FFD valves, and easy-clean design.",
  },
  {
    id:           "hisense-60cm-vertical-hood",
    name:         "Hisense 60cm Vertical Extractor Hood Black Glass",
    slug:         "hisense-60cm-vertical-hood",
    brand:        "Hisense",
    category:     "KITCHEN",
    subcategory:  "built-in",
    price:        18999,
    comparePrice: 22999,
    isFeatured:   false,
    images:       ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.5, reviewCount: 0,
    description: "Hisense 60cm vertical extractor hood. 3-speed fan, LED lighting, aluminium grease filter. Sleek black glass chimney design.",
  },
  {
    id:           "hisense-90cm-vertical-hood",
    name:         "Hisense 90cm Vertical Extractor Hood Black Glass",
    slug:         "hisense-90cm-vertical-hood",
    brand:        "Hisense",
    category:     "KITCHEN",
    subcategory:  "built-in",
    price:        22999,
    comparePrice: 27999,
    isFeatured:   false,
    images:       ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.6, reviewCount: 0,
    description: "Hisense 90cm vertical extractor hood. Powerful 750m³/hr extraction, 3-speed, LED lighting, aluminium grease filter. Black glass finish.",
  },
  {
    id:           "samsung-55-4k-qled-smart-tv",
    name:         "Samsung 55\" 4K QLED Smart TV",
    slug:         "samsung-55-4k-qled-smart-tv",
    brand:        "Samsung",
    category:     "AUDIO_TV",
    subcategory:  "smart-tvs",
    price:        79999,
    comparePrice: 94999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.9, reviewCount: 0,
    description: "Samsung 55\" 4K QLED Smart TV. Quantum Dot technology, Tizen OS, voice control, multiple HDMI/USB ports.",
  },
  {
    id:           "samsung-galaxy-a55-5g-256gb",
    name:         "Samsung Galaxy A55 5G 8GB/256GB",
    slug:         "samsung-galaxy-a55-5g-256gb",
    brand:        "Samsung",
    category:     "SMARTPHONES",
    subcategory:  "phones",
    price:        55999,
    comparePrice: 62999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.7, reviewCount: 0,
    description: "Samsung Galaxy A55 5G. 6.6\" Super AMOLED, Exynos 1480, 50MP triple camera, 5000mAh battery. 8GB RAM / 256GB storage.",
  },
  {
    id:           "hp-15-laptop-i5-8gb-512gb",
    name:         "HP 15 Laptop Intel Core i5 8GB RAM 512GB SSD",
    slug:         "hp-15-laptop-i5-8gb-512gb",
    brand:        "HP",
    category:     "LAPTOPS",
    subcategory:  "laptops",
    price:        68999,
    comparePrice: 78999,
    isFeatured:   true,
    images:       ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80&auto=format&fit=crop"],
    avgRating: 4.8, reviewCount: 0,
    description: "HP 15.6\" laptop with Intel Core i5 12th Gen, 8GB DDR4 RAM, 512GB SSD. Full HD display, Windows 11, backlit keyboard.",
  },
];

export const STATIC_FEATURED = STATIC_PRODUCTS.filter(p => p.isFeatured);
export const STATIC_KITCHEN  = STATIC_PRODUCTS.filter(p => p.category === "KITCHEN");
export const STATIC_LATEST   = STATIC_PRODUCTS.slice(0, 4);
